### ISSUE TITLE
[Doubt/Question] How to remove intermediate pages from Navigation stack

### ISSUE THREAD

**Issue by talk2stephan** [xamarinhq/xamu-infrastructure#20]
![image](https://user-images.githubusercontent.com/38721948/46521830-20b6fe00-c881-11e8-98ce-2ac7bb506b40.png)

As I described in the image I am navigating from my home page then Page A-> B -> C ->D. Once I reach page D, I need to skip / remove the page B and C and when the user press on a button in D, I need to move back to A. I can see a method called **PopToRootAsync()** that will navigate me back to my home screen. But how I can navigate back to a page that is not the root page? Or simply how i can remove some intermediate page from my back stack?

Could you please suggest a way to do the same using our framework project?

**Comment by markjulmar** [comment]
The easiest way is to get the `INavigationPageService` interface from the service locator, cast it to a `FormsNavigationPageService` and then get the `Navigation` property. That's the actual `INavigation` interface from Xamarin.Forms -- you can then use all the methods present .. for example, [RemovePage](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.inavigation.removepage?view=xamarin-forms).

This isn't exposed to the library because it completely breaks the abstraction - you must know about the exact `ContentPage` objects you want to work with. No way to get around that today - so for now, drop down to this level and you can then do whatever you want. If you don't know the pages, you can use the [NavigationStack](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.inavigation.removepage?view=xamarin-forms) property to walk the pages.

Hope that helps!
mark
